### ISSUE TITLE
Batching of writes

### ISSUE THREAD

**Issue by andymac4182** [pootzko/InfluxData.Net#5]
I have a few apps that will write high volumes of points from a single application. It would be good if I could just write these and they would be batched internally in InfluxData. 

If you like the idea and can point me in the right direction I can look at implementing a WriteBatched method that will allow the batching of data to be written per database.

**Comment by pootzko** [comment]
Hi,

batching already exists. `influxDbClient.Client.WriteAsync()` has a second overload which accepts `IEnumerable<Point>` so you can use that. 

Or did you mean something like batching in intervals (for example every few seconds) where you could simply commit single/multiple points within that time frame and the library would trigger every X seconds and submit all the commits to the database?

Perhaps something like this?

```cs
public class ReadingsCollectionHandler
{
    /// <summary>
    /// Concurrent readings queue.
    /// <see cref="http://www.codethinked.com/blockingcollection-and-iproducerconsumercollection"/>
    /// </summary>
    public BlockingCollection<ReadingMessageDTO> ReadingsCollection { get; set; }

    private InfluxDbProvider _influxDbProvider;

    public ReadingsCollectionHandler()
    {
        _influxDbProvider = new InfluxDbProvider(); // This is just a simple wrapper around InfluxData.Net

        ReadingsCollection = new BlockingCollection<ReadingMessageDTO>();
    }

    public async Task RegisterReadingsQueueHandler()
    {
        await Task.Delay(1000);
        HandleReadingsQueue();
        RegisterReadingsQueueHandler();
    }

    private async Task HandleReadingsQueue()
    {
        var readingsCount = ReadingsCollection.Count;
        IList<ReadingMessageDTO> readings = new List<ReadingMessageDTO>();

        for (var i = 0; i < readingsCount; i++)
        {
            ReadingMessageDTO reading;
            var dequeueSuccess = ReadingsCollection.TryTake(out reading);

            if (dequeueSuccess)
            {
                readings.Add(reading);
            }
            else
            {
                throw new Exception("Could not dequeue the collection");
            }
        }

        if (readings.Count > 0)
        {
            await _influxDbProvider.SaveReadings(readings);
        }
    }
}
```

That's kind of what I used to batch stuff in a project I'm working on. The only thing left in this example is to fill the `ReadingsCollection` using `.Add()`. I used the `BlockingCollection` because I have a multi-threaded environment so this was a very convenient way of dealing with a thread-safe collection.

I didn't think about how to package this nicely into the library but you could try if you want. :)

**Comment by andymac4182** [comment]
I was talking about batching at time intervals since I have a large number of single write events and don't want to get locked with number of HTTP requests. I was looking at implementing it in the library since I will probably end up using it in multiple projects. I will have a read over your example and see what I can do :smiley:. Thanks for the example of what you did.

**Comment by pootzko** [comment]
Cool! You're welcome. :)
