### ISSUE TITLE
silently hanging

### ISSUE THREAD

**Issue by awb99** [pootzko/InfluxData.Net#71]
When I try to connect, I do get a silent timeout. My  code:
```
           var influxDbClient = new InfluxDbClient("http://mydomain.com:8086/", "user", "pwd", InfluxDbVersion.v_1_0_0);
               Console.WriteLine("Pinging..");
               var responseP = await influxDbClient.Diagnostics.PingAsync();
               Console.WriteLine("Pinging..Done");
```
I use Windows 10 Home with .net core 2.0 and JetBrains Rider IDE. I downloade the latest
InfluxData.Net libraries via "paket". My server runs influx 1.0.2 on debian stretch linux.

I can connect to my influxdb without any problems via InfluxDB Studio.
In my example above, I never get the "Pinging..Done" printout. 

Any ideas?

**Comment by awb99** [comment]
I now cloned the influxdata project and compiled it and added a demo project 

Curl works:
```
curl http://myhost.com:8086/ping
```
Curl has result code 204. And in the reponse headers I see the influxdb version.

ClientRequestBase.cs line 115 call just hangs:
```
  return await this.Configuration.HttpClient.SendAsync(request, completionOption, cancellationToken).ConfigureAwait(false);
  ```

In a webbrowser MS Edge I can see the same 204 response as in curl. In Chrome  I also cannot see responses.

Very strange!

**Comment by awb99** [comment]
https://stackoverflow.com/questions/35364992/httpclient-sendasync-sits-and-never-progress-even-though-the-data-sent-is-proce

I guess that this is the issue.  All async funcions have to return a task?

**Comment by awb99** [comment]
I resolved the issue: All awaits of any InfluxDB data queries need to happen inside a function that is "async Task<int> demo ()" Otherwise it seems that the Http calls that are made inside the library are forever blocking.

**Comment by tihomir-kit** [comment]
Hi, yes - async functions should return tasks. And using `.Result` should be avoided. Please see [this](http://www.anthonysteele.co.uk/AsyncBasicMistakes). Your calling function (the one that's calling the influxdata.net lib functions) should also await otherwise it will run in a "fire and forget" mode and you'll end up having strange results (you won't be able to debug the method when you attach to the process, sometimes you might not get a result, etc..). So the issue you were having is not really specific to the library itself it's more of the way async/await is supposed to be used.

Can I consider this resolved and close the issue?

**Comment by awb99** [comment]
Issue is closed for sure!  I kept it open, because I believe that a demo project added to the library would make sense.  Otherwise one might end stuck and not start using this fantastic library!
