### ISSUE TITLE
[Question] WriteAsync default behaviour

### ISSUE THREAD

**Issue by Svetomechc** [pootzko/InfluxData.Net#73]
Greetings. I have a rather simple question. What happens when you try to call `_client.Client.WriteAsync(point, "someNonexistentDb")`? Will one be created for you? Or nothing will happen / an exception will be thrown?

**Comment by ryantheleach** [comment]
@Svetomechc That entirely depends on the influx config.

**Comment by tihomir-kit** [comment]
I know this is probably not what you want to hear but @ryantheleach is right. It's not the job of this "adapter library" to take care of that, you as a developer should handle that. 

Some people might not want the library to be creating new DB's in case they made a typo in their code for example.

**Comment by Svetomechc** [comment]
Sounds fair, actually.

**Comment by tihomir-kit** [comment]
I think you should probably get an exception form the influx response though.

**Comment by Svetomechc** [comment]
Thanks again. 

Btw, @pootzko, do you have any plans on keeping this library up to date? I mean, testing against **1.5.x**, supporting [Flux](https://www.influxdata.com/blog/introducing-flux-editor-in-chronograf/), etc. ?

**Comment by tihomir-kit** [comment]
I will add a few more features and merge a few PRs in about a month or two when my schedule frees up a bit. And I'll of course run the tests I have against v1.5 (I believe it should all work fine though, as it has been since ~v1.1 where there weren't any issues and the lib just kept working with the newest versions).

I don't think I'll be implementing Flux in the near future though. I don't need it at work at the moment (until Influx decides to deprecate the old query language they're using) and I currently have other things I'm pursuing privately. This would eat up too much of my time.

**Comment by Svetomechc** [comment]
I too am not ready to adopt a new query language at work. Hopely, they'll continue to support InfluxQL for the time being.
