### ISSUE TITLE
Why not support .net 4.5.2 ?

### ISSUE THREAD

**Issue by GF-Huang** [pootzko/InfluxData.Net#78]

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/39546979-c2984454-4e88-11e8-9890-424de102ad9d.png)
Win10 1709, vs2017

**Comment by tihomir-kit** [comment]
Sorry, I don't read Asian symbols! ;D Kidding.. :)

It's actually because of the .Net Standard support. .Net Standard requires at least .Net 4.6.1. There might be a way to support older .Net versions somehow as well, but to be hones I don't have the time for that. Your best bet would be to fork, ditch the .Net Standard support and lower the target framework version to suit your needs. I think the code will all work fine, but you'll need to make a custom build of the DLL and then use it in your app.

Not sure that really helps you but.. at least it's a point into the right direction.

**Comment by GF-Huang** [comment]
well, thanks for your reply !
I'll try that :)
